### ISSUE TITLE
Remove wrap of itkLabelSetMorphBaseImageFilter

### ISSUE THREAD

**Issue by phcerdan** [InsightSoftwareConsortium/LabelErodeDilate#12]
Python user is not interested in extending base classes. The functionality is provided in the derived classes Erode and Dilate, so we should only wrap those two. @jhlegarreta

Also, the base class is not a regular ImageToImageFilter<TInputImage, TOutputImage>, it has that boolean flag that makes the itk_wrap_image_filter not to work.

Wrapping error raised in: https://discourse.itk.org/t/build-error-with-simplefastmutexlock/1393/8

**Comment by thewtex** [comment]
In general, we need to wrap base classes because they can be passed around in Python. The build system also has checks for this.

**Comment by phcerdan** [comment]
Then we need to fix the current wrapping of itkLabelSetMorphBaseImageFilter, opening #13
